### ISSUE TITLE
Version not importing

### ISSUE THREAD

**Issue by peterhollender** [OpenwaterHealth/OpenLIFU-python#19]
`import openlifu` triggers an exception:

```
File ~\git\OpenLIFU-python\src\openlifu\__init__.py:9
      1 """
      2 Copyright (c) 2023 Openwater. All rights reserved.
      3 
      4 openlifu: Openwater Focused Ultrasound Toolkit
      5 """
      7 from __future__ import annotations
----> 9 from ._version import version as __version__
     11 #from . import bf, db, io, plan, seg, sim, xdc, geo
     14 from openlifu.geo import (
     15     Point
     16 )

ModuleNotFoundError: No module named 'openlifu._version' 
      7 from __future__ import annotations
----> 9 from ._version import version as __version__
     11#from . import bf, db, io, plan, seg, sim, xdc, geo
     14 from openlifu.geo import (
     15     Point
     16 )

ModuleNotFoundError: No module named 'openlifu._version'
```

I see `src\openlifu\_version.pyi` but I'm not sure why it isn't importing?

**Comment by ebrahimebrahim** [comment]
It should work as long as you have _installed_ openlifu. This is because the version is [dynamic metadata](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata); see here:
https://github.com/OpenwaterHealth/OpenLIFU-python/blob/e22f0263d086cd14ef75f6be7ea434560db37144/pyproject.toml#L32
So the version info is not generated until you install. This is how the version is allowed to be linked to version control -- the version itself is not committed or manually updated. It's instead derived from how you version things with git!

While developing on openlifu you probably don't want to have to repeatedly pip install install it over and over again every time you change some code and want to test something. So for that I recommend doing an [editable install](https://setuptools.pypa.io/en/latest/userguide/development_mode.html):

```
pip install -e <path to your openlifu folder>
```

so e.g.

```
cd <path to your openlifu folder>
pip -e .
```

Then you can edit the source code freely and you will be editing the thing that was _installed_ to your python environment as well.

> I see `src\openlifu\_version.pyi` but I'm not sure why it isn't importing?

The `_version.pyi` file is not `_version.py`. It's a stub, used to help type checking systems and IDEs and stuff like that. It basically promises that version info will exist and have those types once the package is installed

---

There's some good info hiding in the [contributing.md](https://github.com/OpenwaterHealth/OpenLIFU-python/blob/main/.github/CONTRIBUTING.md)! In #11 I think we should put some of that into the main readme

---

Closing this assuming this was the solution -- thanks for this question and please don't hesitate to re-open if it's not solved
